web_base_dir = ''
app_name = 'GoWebSHH'
db_type = 'sqlite'
db_dsn = 'gowebssh.db'
is_init = true
jwt_secret = 'PcIVQoUtBI7dcPOkhBt7M54iNcwRxRsGVKcYBEVZCYkHNimqdb5F4OklxX4AGakw'
aes_secret = '7iezmwpzw10azdigwnz24nzhhfhrg2mr'
jwt_expire = 7200000000000
status_refresh = 3000000000
client_check = 15000000000
session_secret = 'wHzEIPHl16EWeSlU979BcOwTqcZZd2e7e03SshcVVYC6s5SY7U4TsTTcbT8SaDmb'
address = ''
port = '8899'
cert_file = '/Users/lostfawn/Downloads/WebSSH-u60pro-master/gossh/.GoWebSSH/cert.pem'
key_file = '/Users/lostfawn/Downloads/WebSSH-u60pro-master/gossh/.GoWebSSH/key.key'
